# -*- coding: utf-8 -*-
"""CryptocurrenciesPredictionbyLSTM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aD15g3UdZNC4XJnj7wqoS9n9iTmqKLMk
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

# %cd /content/drive/MyDrive/DA2/

import math
import matplotlib.pyplot as plt
import keras
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping
dsf=pd.read_csv("ETH-USD.csv")
print('Data size:', df.shape)
dsf.head(5)

df = dsf.iloc[500:,:]
(num_row, num_column) = df.shape
print('Number of rows: ',num_row)
num_test = 180
num_train = num_row - num_test

training_set = df.iloc[:+num_train, 4:5].values
test_set = df.iloc[num_train:, 4:5].values
# print(training_set)
# Feature Scaling
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)
# print(training_set_scaled)
# Creating a data structure with 60 time-steps and 1 output
X_train = []
y_train = []
for i in range(60, num_train):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
print(X_train.shape)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(y_train.shape)

print(X_train.shape)
print(y_train.shape)
print(sc)

model = Sequential()
#Adding the first LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
model.add(Dropout(0.2))
# Adding a second LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
# Adding a third LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
# Adding a fourth LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50))
model.add(Dropout(0.2))
# Adding the output layer
model.add(Dense(units = 1))
# Compiling the RNN
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

model.summary()

# Fitting the RNN to the Training set if the data has never been trained 
# import os.path
# from os import path
# path_name = 'Ethereum_PricePredict_1737.h5'
# if path.exists(path_name):
#   print('Data had been trained, loading weights')
#   model.load_weights(path_name)
# else:
#   print('Start training data')
model.fit(X_train, y_train, epochs = 2, batch_size = 32)
  # model.save(path_name)

# Getting the predicted 
dataset_train = df.iloc[:num_train, 4:5]
dataset_test = df.iloc[num_train+1:, 4:5]
dataset_total = pd.concat((dataset_train, dataset_test), axis = 0)
inputs = dataset_total[len(dataset_total) - len(dataset_test) - 60:].values
inputs = inputs.reshape(-1,1)
inputs = sc.transform(inputs)
X_test = []
for i in range(60, 60 + num_test-1):
    X_test.append(inputs[i-60:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
print(X_test.shape)

predicted_stock_price = model.predict(X_test)
#print(predicted_stock_price)
predicted_stock_price = sc.inverse_transform(predicted_stock_price)
#print('after inverse transform:', predicted_stock_price)
# Visualising the results
plt.figure(figsize=(30,8))
plt.plot(dataset_test.values, 'r--', label = 'Real')
plt.plot(predicted_stock_price, 'b', label = 'Predicted')
plt.xticks(np.arange(0,num_test,50))
plt.title('Ethereum Price Prediction')
plt.xlabel('Time')
plt.ylabel('Price')
plt.legend()
#plt.figure(figsize=(1,1))
#plt.rcParams['figure.figsize'] = [10, 5]
plt.show()

MAPE = np.abs(predicted_stock_price - dataset_test.values)
RMSE = np.multiply(MAPE,MAPE)
RMSE = math.sqrt(np.mean(RMSE))/np.mean(dataset_test.values)
MAE = np.mean(MAPE)/np.mean(dataset_test.values)
MAPE = np.divide(MAPE,dataset_test.values)
MAPE = np.mean(MAPE)
print('MAPE = ',MAPE)
print('MAE = ', MAE*100, '%')
print('RMSE = ',RMSE*100, '%')